/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AboutRouteImport } from './routes/about'
import { Route as BusinessRouteImport } from './routes/business'
import { Route as PrivacyPolicyRouteImport } from './routes/privacy-policy'
import { Route as TeamInviteRouteImport } from './routes/team-invite'
import { Route as TermsOfServicesRouteImport } from './routes/terms-of-services'
import { Route as AuthenticatedBookingsRouteImport } from './routes/_authenticated/bookings'
import { Route as AuthenticatedCatalogRouteImport } from './routes/_authenticated/catalog'
import { Route as AuthenticatedDealsRouteImport } from './routes/_authenticated/deals'
import { Route as AuthenticatedGalleryRouteImport } from './routes/_authenticated/gallery'
import { Route as AuthenticatedPackagesRouteImport } from './routes/_authenticated/packages'
import { Route as AuthenticatedProfileRouteImport } from './routes/_authenticated/profile'
import { Route as AuthenticatedReviewsRouteImport } from './routes/_authenticated/reviews'
import { Route as AuthenticatedSalonsRouteImport } from './routes/_authenticated/salons'
import { Route as AuthenticatedTeamRouteImport } from './routes/_authenticated/team'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const BusinessRoute = BusinessRouteImport.update({
  id: '/business',
  path: '/business',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyPolicyRoute = PrivacyPolicyRouteImport.update({
  id: '/privacy-policy',
  path: '/privacy-policy',
  getParentRoute: () => rootRouteImport,
} as any)
const TeamInviteRoute = TeamInviteRouteImport.update({
  id: '/team-invite',
  path: '/team-invite',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsOfServicesRoute = TermsOfServicesRouteImport.update({
  id: '/terms-of-services',
  path: '/terms-of-services',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedBookingsRoute = AuthenticatedBookingsRouteImport.update({
  id: '/bookings',
  path: '/bookings',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedCatalogRoute = AuthenticatedCatalogRouteImport.update({
  id: '/catalog',
  path: '/catalog',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDealsRoute = AuthenticatedDealsRouteImport.update({
  id: '/deals',
  path: '/deals',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedGalleryRoute = AuthenticatedGalleryRouteImport.update({
  id: '/gallery',
  path: '/gallery',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedPackagesRoute = AuthenticatedPackagesRouteImport.update({
  id: '/packages',
  path: '/packages',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedProfileRoute = AuthenticatedProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedReviewsRoute = AuthenticatedReviewsRouteImport.update({
  id: '/reviews',
  path: '/reviews',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSalonsRoute = AuthenticatedSalonsRouteImport.update({
  id: '/salons',
  path: '/salons',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedTeamRoute = AuthenticatedTeamRouteImport.update({
  id: '/team',
  path: '/team',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/business': typeof BusinessRoute
  '/privacy-policy': typeof PrivacyPolicyRoute
  '/team-invite': typeof TeamInviteRoute
  '/terms-of-services': typeof TermsOfServicesRoute
  '/bookings': typeof AuthenticatedBookingsRoute
  '/catalog': typeof AuthenticatedCatalogRoute
  '/deals': typeof AuthenticatedDealsRoute
  '/gallery': typeof AuthenticatedGalleryRoute
  '/packages': typeof AuthenticatedPackagesRoute
  '/profile': typeof AuthenticatedProfileRoute
  '/reviews': typeof AuthenticatedReviewsRoute
  '/salons': typeof AuthenticatedSalonsRoute
  '/team': typeof AuthenticatedTeamRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/business': typeof BusinessRoute
  '/privacy-policy': typeof PrivacyPolicyRoute
  '/team-invite': typeof TeamInviteRoute
  '/terms-of-services': typeof TermsOfServicesRoute
  '/bookings': typeof AuthenticatedBookingsRoute
  '/catalog': typeof AuthenticatedCatalogRoute
  '/deals': typeof AuthenticatedDealsRoute
  '/gallery': typeof AuthenticatedGalleryRoute
  '/packages': typeof AuthenticatedPackagesRoute
  '/profile': typeof AuthenticatedProfileRoute
  '/reviews': typeof AuthenticatedReviewsRoute
  '/salons': typeof AuthenticatedSalonsRoute
  '/team': typeof AuthenticatedTeamRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/about': typeof AboutRoute
  '/business': typeof BusinessRoute
  '/privacy-policy': typeof PrivacyPolicyRoute
  '/team-invite': typeof TeamInviteRoute
  '/terms-of-services': typeof TermsOfServicesRoute
  '/_authenticated/bookings': typeof AuthenticatedBookingsRoute
  '/_authenticated/catalog': typeof AuthenticatedCatalogRoute
  '/_authenticated/deals': typeof AuthenticatedDealsRoute
  '/_authenticated/gallery': typeof AuthenticatedGalleryRoute
  '/_authenticated/packages': typeof AuthenticatedPackagesRoute
  '/_authenticated/profile': typeof AuthenticatedProfileRoute
  '/_authenticated/reviews': typeof AuthenticatedReviewsRoute
  '/_authenticated/salons': typeof AuthenticatedSalonsRoute
  '/_authenticated/team': typeof AuthenticatedTeamRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/business'
    | '/privacy-policy'
    | '/team-invite'
    | '/terms-of-services'
    | '/bookings'
    | '/catalog'
    | '/deals'
    | '/gallery'
    | '/packages'
    | '/profile'
    | '/reviews'
    | '/salons'
    | '/team'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/business'
    | '/privacy-policy'
    | '/team-invite'
    | '/terms-of-services'
    | '/bookings'
    | '/catalog'
    | '/deals'
    | '/gallery'
    | '/packages'
    | '/profile'
    | '/reviews'
    | '/salons'
    | '/team'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/about'
    | '/business'
    | '/privacy-policy'
    | '/team-invite'
    | '/terms-of-services'
    | '/_authenticated/bookings'
    | '/_authenticated/catalog'
    | '/_authenticated/deals'
    | '/_authenticated/gallery'
    | '/_authenticated/packages'
    | '/_authenticated/profile'
    | '/_authenticated/reviews'
    | '/_authenticated/salons'
    | '/_authenticated/team'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AboutRoute: typeof AboutRoute
  BusinessRoute: typeof BusinessRoute
  PrivacyPolicyRoute: typeof PrivacyPolicyRoute
  TeamInviteRoute: typeof TeamInviteRoute
  TermsOfServicesRoute: typeof TermsOfServicesRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/business': {
      id: '/business'
      path: '/business'
      fullPath: '/business'
      preLoaderRoute: typeof BusinessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy-policy': {
      id: '/privacy-policy'
      path: '/privacy-policy'
      fullPath: '/privacy-policy'
      preLoaderRoute: typeof PrivacyPolicyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/team-invite': {
      id: '/team-invite'
      path: '/team-invite'
      fullPath: '/team-invite'
      preLoaderRoute: typeof TeamInviteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms-of-services': {
      id: '/terms-of-services'
      path: '/terms-of-services'
      fullPath: '/terms-of-services'
      preLoaderRoute: typeof TermsOfServicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/bookings': {
      id: '/_authenticated/bookings'
      path: '/bookings'
      fullPath: '/bookings'
      preLoaderRoute: typeof AuthenticatedBookingsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/catalog': {
      id: '/_authenticated/catalog'
      path: '/catalog'
      fullPath: '/catalog'
      preLoaderRoute: typeof AuthenticatedCatalogRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/deals': {
      id: '/_authenticated/deals'
      path: '/deals'
      fullPath: '/deals'
      preLoaderRoute: typeof AuthenticatedDealsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/gallery': {
      id: '/_authenticated/gallery'
      path: '/gallery'
      fullPath: '/gallery'
      preLoaderRoute: typeof AuthenticatedGalleryRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/packages': {
      id: '/_authenticated/packages'
      path: '/packages'
      fullPath: '/packages'
      preLoaderRoute: typeof AuthenticatedPackagesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/profile': {
      id: '/_authenticated/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof AuthenticatedProfileRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/reviews': {
      id: '/_authenticated/reviews'
      path: '/reviews'
      fullPath: '/reviews'
      preLoaderRoute: typeof AuthenticatedReviewsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/salons': {
      id: '/_authenticated/salons'
      path: '/salons'
      fullPath: '/salons'
      preLoaderRoute: typeof AuthenticatedSalonsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/team': {
      id: '/_authenticated/team'
      path: '/team'
      fullPath: '/team'
      preLoaderRoute: typeof AuthenticatedTeamRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedBookingsRoute: typeof AuthenticatedBookingsRoute
  AuthenticatedCatalogRoute: typeof AuthenticatedCatalogRoute
  AuthenticatedDealsRoute: typeof AuthenticatedDealsRoute
  AuthenticatedGalleryRoute: typeof AuthenticatedGalleryRoute
  AuthenticatedPackagesRoute: typeof AuthenticatedPackagesRoute
  AuthenticatedProfileRoute: typeof AuthenticatedProfileRoute
  AuthenticatedReviewsRoute: typeof AuthenticatedReviewsRoute
  AuthenticatedSalonsRoute: typeof AuthenticatedSalonsRoute
  AuthenticatedTeamRoute: typeof AuthenticatedTeamRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedBookingsRoute: AuthenticatedBookingsRoute,
  AuthenticatedCatalogRoute: AuthenticatedCatalogRoute,
  AuthenticatedDealsRoute: AuthenticatedDealsRoute,
  AuthenticatedGalleryRoute: AuthenticatedGalleryRoute,
  AuthenticatedPackagesRoute: AuthenticatedPackagesRoute,
  AuthenticatedProfileRoute: AuthenticatedProfileRoute,
  AuthenticatedReviewsRoute: AuthenticatedReviewsRoute,
  AuthenticatedSalonsRoute: AuthenticatedSalonsRoute,
  AuthenticatedTeamRoute: AuthenticatedTeamRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AboutRoute: AboutRoute,
  BusinessRoute: BusinessRoute,
  PrivacyPolicyRoute: PrivacyPolicyRoute,
  TeamInviteRoute: TeamInviteRoute,
  TermsOfServicesRoute: TermsOfServicesRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
